name: Update Spotify Now Playing SVG

on:
  # This runs the job on a schedule (every 5 minutes)
  schedule:
    - cron: '*/5 * * * *'
  # This allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    
    # Add permissions for the job to be able to write to the repository
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        # Use the latest major version of the checkout action
        uses: actions/checkout@v4

      - name: Update SVG
        run: |
          # Fetch the latest SVG from your Vercel deployment
          curl --silent "https://siddharth25op-spotify-status.vercel.app/api/svg" > now-playing.svg

      - name: Commit and push if changed
        run: |
          # Configure git for the bot user
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Stage the file
          git add now-playing.svg
          
          # Commit and push only if there are staged changes
          # The `git diff --staged --quiet` command correctly checks for changes in the staging area.
          # It will exit with 1 if there are changes, and 0 if there are none.
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update now-playing.svg"
            git push
          else
            echo "No changes detected in now-playing.svg."
          fi
